"""`docs/JOBS.md` must describe the jobs that are actually here.

The manifest is what makes a job family reviewable: `quebraplan.md` 3.4
argues that explicit files are greppable and a parameterised definition is not, so the
readable view has to be generated rather than hoped for. A stale manifest is worse than none,
because it asserts a shape nobody checked.
"""

from __future__ import annotations

import sys
from pathlib import Path
import pytest

pytestmark = pytest.mark.policy


REPO = Path(__file__).resolve().parent.parent
MANIFEST = REPO / "docs" / "JOBS.md"


def test_the_manifest_is_current():
    """Regenerate into memory and compare. Fails when a job changed without regeneration."""
    sys.path.insert(0, str(REPO / "scripts"))
    from make_job_manifest import build

    assert MANIFEST.is_file(), (
        "docs/JOBS.md is missing; run scripts/make_job_manifest.py"
    )
    assert MANIFEST.read_text() == build(), (
        "docs/JOBS.md is stale. Run `python scripts/make_job_manifest.py` and commit it."
    )


def test_every_discovered_job_appears():
    from quebra.core.discovery import discover

    text = MANIFEST.read_text()
    for job_id in discover(REPO / "jobs"):
        assert f"`{job_id}`" in text, f"{job_id} is not in the manifest"


def test_the_generator_does_not_import_the_jobs(tmp_path, monkeypatch):
    """Same rule as discovery: importing a job builds its graph.

    The previous version asserted `discover(tmp_path)` — the wrong function — and then
    `assert gen.build`, the truthiness of a function object. It exercised the generator not
    at all. This points the generator's own `JOBS` constant at a tree whose single job raises
    on import, and calls `build()`.
    """
    sys.path.insert(0, str(REPO / "scripts"))
    import make_job_manifest as gen

    (tmp_path / "boom.py").write_text(
        'JOB_ID = "boom"\nJOB_FAMILY = "demo"\nSEED = 7\n'
        'raise RuntimeError("the manifest generator must not import jobs")\n'
    )
    monkeypatch.setattr(gen, "JOBS", tmp_path)
    rendered = gen.build()
    assert "`boom`" in rendered and "`SEED=7`" in rendered


def test_it_says_it_is_generated():
    text = MANIFEST.read_text()
    assert "GENERATED by" in text and "Do not hand-edit" in text


def test_regenerating_is_idempotent():
    """`build()` twice gives the same text.

    Deliberately does NOT shell out to the generator: `main()` WRITES `docs/JOBS.md`, so a
    test that ran it would repair the very staleness `test_the_manifest_is_current` exists to
    detect — the run reporting the failure would also erase it.
    """
    sys.path.insert(0, str(REPO / "scripts"))
    from make_job_manifest import build

    assert build() == build()


def test_staleness_fires_when_a_JOB_changes_not_only_when_the_file_is_edited(
    tmp_path, monkeypatch
):
    """The staleness test has to notice a job changing, which is the case it exists for.

    Under the old allowlist this could not have been written: editing a seed left `build()`
    byte-identical, because the seed was not in `INTERESTING`.
    """
    sys.path.insert(0, str(REPO / "scripts"))
    import make_job_manifest as gen

    job = tmp_path / "a.py"
    job.write_text('JOB_ID = "a"\nJOB_FAMILY = "f"\nVALIDATION_SEED = 1\n')
    monkeypatch.setattr(gen, "JOBS", tmp_path)
    before = gen.build()
    job.write_text('JOB_ID = "a"\nJOB_FAMILY = "f"\nVALIDATION_SEED = 2\n')
    assert gen.build() != before, "changing a job's seed must change the manifest"
