#!/usr/bin/env python3
"""Regenerate `docs/JOBS.md`, the human-readable view of what each job is.

`quebraplan.md` 3.4 makes the argument: explicit job files are trivially
greppable and diffable, and a parameterised definition hides per-job intent — so generate the
readable view and reviewability survives the abstraction. That argument holds at 12 jobs as
much as at the 63 the plan assumed.

    python scripts/make_job_manifest.py

Reads declarations STATICALLY. Importing a job builds its graph, so a manifest generator that
imported would run every job in the tree to write a table.
"""

from __future__ import annotations

import ast
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
JOBS = REPO / "jobs"
MANIFEST = REPO / "docs" / "JOBS.md"

# Constants that are NOT parameters: the job's own declarations, which have their own
# columns. Everything else that is a module-level uppercase SCALAR is surfaced.
#
# This was an allowlist of ten names, which was wrong in the way allowlists usually are: it
# claimed to hold "the ones that decide what a run MEANS" while silently omitting
# VALIDATION_SEED, ASYMPTOTIC_SIZE_SEED, C3_N_NULL_SIM, TIE_CUTOFF_DISTINCT and four others.
# Editing a seed left the generated manifest byte-identical, so the staleness test could not
# see it either. A rule cannot go stale the way a list does.
DECLARATIONS = frozenset({"JOB_ID", "JOB_FAMILY", "JOB_SWEEP"})

# Scalars only. A job's dataset tuple runs to 34 filenames and its threshold ladder is a
# comprehension; neither belongs in a table meant to be scanned, and both are visible in the
# datasets column or the source.
SCALARS = (int, float, bool, str)


def _constants(tree: ast.Module) -> dict[str, str]:
    """Module-level literal assignments, rendered. Non-literals are skipped, not guessed at."""
    found: dict[str, str] = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            names = [t.id for t in node.targets if isinstance(t, ast.Name)]
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            names = [node.target.id]
        else:
            continue
        for name in names:
            if name in DECLARATIONS or not name.isupper() or name.startswith("_"):
                continue
            try:
                value = ast.literal_eval(node.value)
            except (ValueError, TypeError, SyntaxError):
                # Not a literal (a Dataset(...) call, a comprehension). Skipped on purpose,
                # and visible in the datasets column or the source.
                continue
            if isinstance(value, SCALARS):
                found[name] = repr(value)
    return found


def _datasets(tree: ast.Module) -> list[str]:
    """Dataset paths a job names, as written. Absent for jobs that build paths in a loop."""
    out: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and getattr(node.func, "id", "") == "Dataset":
            for kw in node.keywords:
                if kw.arg == "path" and isinstance(kw.value, ast.Constant):
                    out.append(str(kw.value.value))
    return sorted(set(out))


def _includes(tree: ast.Module) -> list[str]:
    out: list[str] = []
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Call)
            and getattr(node.func, "attr", "") == "include"
            and node.args
            and isinstance(node.args[0], ast.Constant)
        ):
            out.append(str(node.args[0].value))
    return sorted(set(out))


def build() -> str:
    from quebra.core.discovery import discover

    jobs = discover(JOBS)
    by_family: dict[str, list] = {}
    for declared in jobs.values():
        by_family.setdefault(declared.family or "uncategorised", []).append(declared)

    lines = [
        "# Jobs",
        "",
        "GENERATED by `scripts/make_job_manifest.py`. Do not hand-edit;",
        "`tests/test_job_manifest.py` fails when this file is stale.",
        "",
        "Every job declares a `JOB_ID` (the logical name `job.include` resolves) and a",
        "`JOB_FAMILY` (its category). Neither is its directory: a job can move without",
        "breaking any composite, and recategorising costs one string edit.",
        "",
        f"{len(jobs)} jobs in {len(by_family)} families.",
        "",
    ]

    for family in sorted(by_family):
        lines.append(f"## {family}")
        lines.append("")
        lines.append("| JOB_ID | file | datasets | includes | parameters |")
        lines.append("|---|---|---|---|---|")
        for declared in sorted(by_family[family], key=lambda d: d.job_id):
            tree = ast.parse(declared.path.read_text(encoding="utf-8"))
            try:
                rel = declared.path.relative_to(REPO)
            except ValueError:
                # A job outside the repository root (or a test pointing JOBS elsewhere).
                # Render the path as given rather than raising.
                rel = declared.path
            datasets = _datasets(tree)
            includes = _includes(tree)
            params = _constants(tree)
            lines.append(
                f"| `{declared.job_id}` | `{rel}` "
                f"| {'<br>'.join(f'`{d}`' for d in datasets) or '—'} "
                f"| {'<br>'.join(f'`{i}`' for i in includes) or '—'} "
                f"| {'<br>'.join(f'`{k}={v}`' for k, v in sorted(params.items())) or '—'} |"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(build())
    print(f"wrote {MANIFEST} ({MANIFEST.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
